### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by snelbops** [tagawa/AI-Podcast-Creator#1]
I got this error with the feed: SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate.

To solve this I ran the Install Certficates.command in the Python application folder. Here's the info I followed: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by tagawa** [comment]
Thanks for clarifying the problem and what you did to solve it. I'll close this issue as it's now fixed, but this will stay public in case others find it helpful.
